#!/bin/bash

#Color input
#echo "$B" this text is blue "$R"
BLACK="$(tput setaf 0)" #black
R="$(tput setaf 1)" #Red
G="$(tput setaf 2)" #Green
Y="$(tput setaf 3)" #Yellow
B="$(tput setaf 4)" #blue
M="$(tput setaf 5)" #Magenta
C="$(tput setaf 6)" #Cyan
W="$(tput setaf 7)" #White
D="$(tput sgr0)" #reset/defult
bold="$(tput bold)" #bold
dim="$(tput dim)" #dim/ half bright





clear
echo "$R""$bold"$' 
 __    __ _  __ _       _      _  __ 
/ / /\ \ (_)/ _(_)     | | ___(_)/ _|
\ \/  \/ / | |_| |_____| |/ _ \ | |_ 
 \  /\  /| |  _| |_____| |  __/ |  _|
  \/  \/ |_|_| |_|     |_|\___|_|_|    ©
                                     
'
echo "$D"

echo "$B""$bold"Checking if "$R"dialog"$B" is installed:"$D"
sleep 2 &&

    if (pacman -Q dialog >/dev/null) ; 
    then 
	echo "$G""$bold"dialog is installed"$D"; 
    else 
	echo "$R""$bold"dialog is NOT installed"" && 
	sleep 1 && 
	echo "dialog is needed to make this script work" && 
	echo ""dialog will be installed now..."$D" && 
	sleep 1 && 
	sudo pacman -S dialog; 
    fi


sleep 2 &&
clear


echo "$R""$bold"$' 
 __    __ _  __ _       _      _  __ 
/ / /\ \ (_)/ _(_)     | | ___(_)/ _|
\ \/  \/ / | |_| |_____| |/ _ \ | |_ 
 \  /\  /| |  _| |_____| |  __/ |  _|
  \/  \/ |_|_| |_|     |_|\___|_|_|    ©
                                     
'
echo "$D"

echo "$B""$bold"Checking if "$R"Gzip"$B" is installed:"$D"
sleep 2 &&

    if (pacman -Q gzip >/dev/null) ; 
    then 
	echo "$G""$bold"Gzip is installed"$D"; 
    else 
	echo "$R""$bold"Gzip is NOT installed"" && 
	sleep 1 && 
	echo "Gzip is needed to make this script work" && 
	echo ""Gzip will be installed now..."$D" && 
	sleep 1 && 
	sudo pacman -S gzip; 
    fi


sleep 2 &&
clear

echo "$R""$bold"$' 
 __    __ _  __ _       _      _  __ 
/ / /\ \ (_)/ _(_)     | | ___(_)/ _|
\ \/  \/ / | |_| |_____| |/ _ \ | |_ 
 \  /\  /| |  _| |_____| |  __/ |  _|
  \/  \/ |_|_| |_|     |_|\___|_|_|    ©
                                     
'
echo "$D"

echo "$B""$bold"Checking if "$R"NetworkManager"$B" is installed:"$D"
sleep 2 &&

    if (pacman -Q networkmanager >/dev/null) ; 
    then 
	echo "$G""$bold"NetworkManager is Installed"$D";
    else 
	echo ""
	echo ""	
	echo "$R""$bold"Warning Networkmanager is Not Installed"" &&
	echo "Warning this installation is not recomended if your a noob!" &&
	echo "If you know how to dissable all previous networkmanagers you have had in systemctl this will not be a problme" &&
	echo "eg. systemctl stop netctl-auto@WLXXX DEVICE.service , systmctl disable netctl , systmctl disable netctl-auto@WLXXX DEVICE.service" &&
	echo "tip: write in systemctl disable net and then hit tab many times and it will pop up" &&
	echo ""
	echo ""

	echo "Installing Networkmanager..." &&
	echo "Press ctrl+c to stop or close down the terminal"
	echo "press enter to continue...$D" &&
	read enter &&
	sudo pacman -S networkmanager &&
	echo ""

	echo ""
	echo ""
	echo "$R""$bold"installing recomended packages""
	echo "Press ctrl+c to stop or close down the terminal"
	echo "$B"press enter to continue..."$D" &&
	read enter &&

	sudo pacman -S dnsmasq network-manager-applet networkmanager-openconnect networkmanager-openvpn networkmanager-pptp networkmanager-vpnc ntp networkmanager-dispatcher-ntpd &&

	echo ""
	echo "$B""$bold" &&
	echo "Enabling networkmanager in systemctl"
	echo "Press ctrl+c to stop or close down the terminal"
	echo "Press enter to continue..." &&
	read enter &&
	sudo systemctl enable NetworkManager &&
	echo "" &&
	echo ""done"$D" &&
	sleep 2 ;

fi

sleep 2 &&
clear
echo "$R""$bold"$' 
 __    __ _  __ _       _      _  __ 
/ / /\ \ (_)/ _(_)     | | ___(_)/ _|
\ \/  \/ / | |_| |_____| |/ _ \ | |_ 
 \  /\  /| |  _| |_____| |  __/ |  _|
  \/  \/ |_|_| |_|     |_|\___|_|_|    ©
                                     
'
echo "$D"


echo ""
echo "$B""$bold"'What version of '"$G"'WiFi-leif'"$B"' do you want? defult=1'""
echo "" 
echo "$G"'1 = GUI (wifi-leif will launch gui version)'""
echo "2 = TEXT (wifi-leif will launch text version)"
echo "3 = BOTH, GUI AS DEFULT(wifi-leif-text to launch text version)"
echo "4 = BOTH, TEXT AS DEFULT(wifi-leif-gui to launch gui version)"
echo ""'5 = BOTH, NON AS DEFULT(wifi-leif-text / wifi-leif-gui)'"$D"
echo ""
echo "" 
read ans
echo ""
case $ans in

1|gui|Gui|GUI|"")
echo ""
echo ""
echo "$B""$bold""Are you sure you want to continue installing "$R"WiFi-leif GUI"$B" version? (y/n)""$D"
read yn
if [[ "$yn" == "back" || "$yn" == "exit" || "$yn" == "" || "$yn" == "n" || "$yn" == "N" ]] ; then echo "$R""$bold""exiting...." && echo "This installasion was NOT complete..""$D" && exit ; fi &&

cd ~/bash/wifi-leif/ &&
chmod +x wifi-leif-logo &&
chmod +x wifi-leif-text &&
chmod +x wifi-leif-gui &&
chmod +x wifi-leif-logo-gui &&
chmod +x wifi-leif &&
echo "wifi-leif-gui" >> ~/bash/wifi-leif/wifi-leif &&
sudo cp wifi-leif /usr/local/bin &&
sudo cp wifi-leif-logo /usr/local/bin &&
sudo cp wifi-leif-logo-gui /usr/local/bin &&
sudo cp wifi-leif-gui /usr/local/bin &&
sudo cp man-wifi-leif wifi-leif.1 &&
gzip wifi-leif.1 &&
sudo mv wifi-leif.1.gz /usr/share/man/man1 &&
echo "$G""$bold""All done thank you for installing Wifi-leif""$D"


;;

2|text|Text|TEXT)
echo ""
echo ""
echo "$B""$bold""Are you sure you want to continue installing "$R"WiFi-leif TEXT"$B" version? (y/n)""$D"
read yn
if [[ "$yn" == "back" || "$yn" == "exit" || "$yn" == "" || "$yn" == "n" || "$yn" == "N" ]] ; then echo "$R""$bold""exiting...." && echo "This installasion was NOT complete..""$D" && exit ; fi &&

cd ~/bash/wifi-leif/ &&
chmod +x wifi-leif-logo &&
chmod +x wifi-leif-text &&
chmod +x wifi-leif-gui &&
chmod +x wifi-leif-logo-gui &&
chmod +x wifi-leif &&
echo "wifi-leif-text" >> ~/bash/wifi-leif/wifi-leif &&
sudo cp wifi-leif /usr/local/bin &&
sudo cp wifi-leif-logo /usr/local/bin &&
sudo cp wifi-leif-logo-gui /usr/local/bin &&
sudo cp wifi-leif-text /usr/local/bin &&
sudo cp man-wifi-leif wifi-leif.1 &&
gzip wifi-leif.1 &&
sudo mv wifi-leif.1.gz /usr/share/man/man1 &&
echo "$G""$bold""All done thank you for installing Wifi-leif""$D"
;;

3|both-gui|Both-Gui|Both-gui|BOTH-GUI)
echo ""
echo ""
echo "$B""$bold""Are you sure you want to continue installing "$R"WiFi-leif both version"$B" with "$R"GUI as defult"$B"? (y/n)""$D"
read yn
if [[ "$yn" == "back" || "$yn" == "exit" || "$yn" == "" || "$yn" == "n" || "$yn" == "N" ]] ; then echo "$R""$bold""exiting...." && echo "This installasion was NOT complete..""$D" && exit ; fi &&

cd ~/bash/wifi-leif/ &&
chmod +x wifi-leif-logo &&
chmod +x wifi-leif-text &&
chmod +x wifi-leif-gui &&
chmod +x wifi-leif-logo-gui &&
chmod +x wifi-leif &&
echo "wifi-leif-gui" >> ~/bash/wifi-leif/wifi-leif &&
sudo cp wifi-leif /usr/local/bin &&
sudo cp wifi-leif-logo /usr/local/bin &&
sudo cp wifi-leif-logo-gui /usr/local/bin &&
sudo cp wifi-leif-gui /usr/local/bin/wifi-leif-gui &&
sudo cp wifi-leif-text /usr/local/bin/wifi-leif-text &&
sudo cp man-wifi-leif wifi-leif.1 &&
gzip wifi-leif.1 &&
sudo mv wifi-leif.1.gz /usr/share/man/man1 &&
echo "$G""$bold""All done thank you for installing Wifi-leif""$D"
;;

4|both-text|Both-Text|Both-text|BOTH-TEXT)
echo ""
echo ""
echo "$B""$bold""Are you sure you want to continue installing "$R"WiFi-leif both version"$B" with "$R"TEXT as defult"$B"? (y/n)""$D"
read yn
if [[ "$yn" == "back" || "$yn" == "exit" || "$yn" == "" || "$yn" == "n" || "$yn" == "N" ]] ; then echo "$R""$bold""exiting...." && echo "This installasion was NOT complete..""$D" && exit ; fi &&

cd ~/bash/wifi-leif/ &&
chmod +x wifi-leif-logo &&
chmod +x wifi-leif-text &&
chmod +x wifi-leif-gui &&
chmod +x wifi-leif-logo-gui &&
chmod +x wifi-leif &&
echo "wifi-leif-text" >> ~/bash/wifi-leif/wifi-leif &&
sudo cp wifi-leif /usr/local/bin &&
sudo cp wifi-leif-logo /usr/local/bin &&
sudo cp wifi-leif-logo-gui /usr/local/bin &&
sudo cp wifi-leif-gui /usr/local/bin/wifi-leif-gui &&
sudo cp wifi-leif-text /usr/local/bin/wifi-leif-text &&
sudo cp man-wifi-leif wifi-leif.1 &&
gzip wifi-leif.1 &&
sudo mv wifi-leif.1.gz /usr/share/man/man1 &&
echo "$G""$bold""All done thank you for installing Wifi-leif""$D"
;;

5|both|Both|BOTH)
echo ""
echo ""
echo "$B""$bold""Are you sure you want to continue installing "$R"wifi-leif-gui"$B" and "$R"wifi-leif-text"$B" and use "$R"NON as defult"$B"? (y/n)""$D"
read yn
if [[ "$yn" == "back" || "$yn" == "exit" || "$yn" == "" || "$yn" == "n" || "$yn" == "N" ]] ; then echo "$R""$bold""exiting...." && echo "This installasion was NOT complete..""$D" && exit ; fi &&

cd ~/bash/wifi-leif/ &&
chmod +x wifi-leif-logo &&
chmod +x wifi-leif-text &&
chmod +x wifi-leif-gui &&
chmod +x wifi-leif-logo-gui &&
sudo cp wifi-leif-logo /usr/local/bin &&
sudo cp wifi-leif-logo-gui /usr/local/bin &&
sudo cp wifi-leif-gui /usr/local/bin/wifi-leif-gui &&
sudo cp wifi-leif-text /usr/local/bin/wifi-leif-text &&
sudo cp man-wifi-leif wifi-leif.1 &&
gzip wifi-leif.1 &&
sudo mv wifi-leif.1.gz /usr/share/man/man1 &&
echo "$G""$bold""All done thank you for installing Wifi-leif""$D"
;;

*)
echo "$R""$bold""sorry wrong command"
echo "exiting...."
echo "this installasion was NOT complete...""$D"
sleep 2
exit
;;
esac
