#!/bin/bash

#Color input
#echo "$B" this text is blue "$R"
BLACK="$(tput setaf 0)" #black
R="$(tput setaf 1)" #Red
G="$(tput setaf 2)" #Green
Y="$(tput setaf 3)" #Yellow
B="$(tput setaf 4)" #blue
M="$(tput setaf 5)" #Magenta
C="$(tput setaf 6)" #Cyan
W="$(tput setaf 7)" #White
D="$(tput sgr0)" #reset/defult
bold="$(tput bold)" #bold
dim="$(tput dim)" #dim/ half bright




echo "$R""$bold"$' 
 __    __ _  __ _       _      _  __ 
/ / /\ \ (_)/ _(_)     | | ___(_)/ _|
\ \/  \/ / | |_| |_____| |/ _ \ | |_ 
 \  /\  /| |  _| |_____| |  __/ |  _|
  \/  \/ |_|_| |_|     |_|\___|_|_|    ©
                                     
'
echo "$D"
