#!/bin/bash

logo=`wifi-leif-logo`

#Color input
#echo "$B" this text is blue "$R"
BLACK="$(tput setaf 0)" #black
R="$(tput setaf 1)" #Red
G="$(tput setaf 2)" #Green
Y="$(tput setaf 3)" #Yellow
B="$(tput setaf 4)" #blue
M="$(tput setaf 5)" #Magenta
C="$(tput setaf 6)" #Cyan
W="$(tput setaf 7)" #White
D="$(tput sgr0)" #reset/defult
bold="$(tput bold)" #bold
dim="$(tput dim)" #dim/ half bright


clear
echo "$logo"
echo "$D"
echo ""
echo ""
echo "$G""$bold"Please select options:"$D"
echo ""
echo "$G""$bold"
echo '1)  - list		|	(List avilible WiFi accses points)'
echo '2)  - rescan		|	(Rescan WiFi accses points)'
echo '3)  - on		|	(Turn WiFi ON)'
echo '4)  - off		|	(Turn WiFi OFF)'
echo '5)  - status		|	(Show status of the wifi)'
echo '6)  - connect		|	(Connect to a WiFi accses point)'
echo '7)  - disconnect	|	(Disconnect from a Wifi accses point)'
echo '8)  - ip-local		|	(Shows local IP)'
echo '9)  - ip-public		|	(Shows public IP)'
echo '10) - ping		|	(Ping a ip or host)'
echo '11) - exit		|	(Exit wifi-leif)'
echo "$D"

read case

case $case in

1|list|List|list,|LIST)
echo ""
echo ""
echo "$B""$bold"Wifi avalible:"$D"
echo ""
echo "$G""$bold" &&
nmcli d wifi list &&
echo "$D" &&
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text ;;

2|rescan|Rescan|rescan,|RESCAN)
echo ""
echo "$B""$bold"'Scanning for avilable wifi' &&
nmcli d wifi rescan
echo ""
sleep 1
echo "$G""Scanning is completted""$D"
echo ""
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text ;;

3|on|On|on,|ON)
echo ""
echo "$G""$bold"Turning on wifi"$D"
echo ""
echo "$G""$bold"Wifi is now:"" &&
nmcli r wifi on
nmcli r wifi &&
echo "$D" &&
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text ;;

4|off|Off|off,|OFF)
echo ""
echo "$R""$bold"Turning off wifi"$D"
echo ""
echo "$R""$bold"Wifi is now:"" &&
nmcli r wifi off
nmcli r wifi &&
echo "$D" &&
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text ;;


5|status|Status|status,|STATUS)
echo ""
echo ""
nmcli d status &&
echo ""
echo "$B""$bold"To go back to menu, type "$R"back "$B"or "$R"exit "$B"or "$R"hit enter "$D"
echo ""
echo "$B""$bold"'Please write in '"$R"'wifi DEVICE'"$B"' (see info above)'"$D"
echo ""
read wifi
if [[ "$wifi" == "back" || "$wifi" == "exit" || "$wifi" == "" ]] ; then wifi-leif-text ; fi &&
echo ""
echo ""
echo "$B""$bold"Wifi status on $wifi:"$D"
ip link show $wifi &&
echo ""
echo ""
iw dev $wifi station dump &&
echo ""
wifi
echo ""
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text ;;

6|connect|Connect|connect,|CONNECT)
echo ""
echo ""
nmcli d wifi list &&
echo ""
echo ""
echo "$R""$bold"If wifi is connected please dissconect first"$D"
sleep 3
echo ""
echo ""
nmcli d status &&
echo ""
echo "$B""$bold"To go back to menu, type "$R"back "$B"or "$R"exit "$B"or "$R"hit enter "$D"
echo ""
echo "$B""$bold"'Plesae write in '"$R"'wifi DEVICE'"$B"' (see info above)'"$D"
echo ""
read wifi &&
echo ""

if [[ "$wifi" == "back" || "$wifi" == "exit" || "$wifi" == "" ]] ; then wifi-leif-text ; fi &&


echo "$bold"
nmcli d wifi rescan &&
nmcli d wifi list &&
echo ""
echo "$B"'Please write in '"$R"'accses name(WiFi-SSID)'"$B"' the wifi you want to connect to'"$D"
echo ""
read WiFiSSID
if [[ "$WiFiSSID" == "back" || "$WiFiSSID" == "exit" || "$WiFiSSID" == "" ]] ; then wifi-leif-text ; fi &&
echo ""
echo "$B""$bold"'Please Write in '"$R"'password'"$B"' for the wifi'"$D"
echo ""
read WiFipassword &&
if [[ "$WiFipassword" == "back" || "$WiFipassword" == "exit" ]] ; then wifi-leif-text ; fi &&
nmcli d wifi connect $WiFiSSID password $WiFipassword iface $wifi &&
echo ""
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text
;;

7|disconnect|Disconnect|disconnect,|DISCONNECT)
echo ""
echo ""
nmcli d status &&
echo ""
echo "$B""$bold"To go back to menu, type "$R"back "$B"or "$R"exit "$B"or "$R"hit enter "$D"
echo ""
echo "$B""$bold"'Plese write in '"$R"'wifi DEVICE'"$B"' (see info above)'"$D"
echo ""
read wifi

if [[ "$wifi" == "back" || "$wifi" == "exit" || "$wifi" == "" ]] ; then wifi-leif-text ; fi &&

echo ""
echo ""
echo "$R""$bold"'Disconnecting the wifi point'"$D"
echo ""
nmcli d disconnect iface $wifi
echo ""
echo ""
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text ;;

8|ip-local|IP-LOCAL|Ip-local|ip-local,)
echo ""
echo ""
echo "$R""$bold"'Your Local ip is:'
echo ""
ip route get 8.8.8.8 | awk '{print $NF; exit}' &&
echo ""
echo ""
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text ;;


9|ip-public|IP-PUBLIC|Ip-Public|ip-public,)
echo ""
echo "$R""$bold"'This may take a moment'
echo ""
echo 'Your Ip address is:'
echo ""
curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'  &&
echo "$D"
echo ""
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text ;;


10|ping|Ping|ping,|PING)
echo ""
echo "$B""$bold"To go back to menu, type "$R"back "$B"or "$R"exit "$B"or "$R"hit enter "$D"
echo ""
echo "$B""$bold"'What '"$R"'ip-address / web-address'"$B"' do you want to ping?'"$D"
echo ""
read ip
echo ""

if [[ "$ip" == "back" || "$ip" == "exit" || "$ip" == "" ]] ; then wifi-leif-text ; fi &&

echo ""
echo "$B""$bold"'how many times do you want to ping?'"$D"
read num
if [[ "$um" == "back" || "$num" == "exit" || "$num" == "" ]] ; then wifi-leif-text ; fi &&
ping -c$num $ip
echo ""
echo ""
echo "$B""$bold"press enter to continue..."$D"
read yes &&
wifi-leif-text ;;

11|exit|Exit|exit,EXIT)
echo ""
echo ""
echo "$B""$bold"'Thank you for using wifi-leif'"$d"
echo ""
echo "$G""$bold"'Exiting...'"$d"
echo ""
exit ;;

*)
echo ""
echo ""
echo "$R""$bold"'ERROR WRONG COMMAND!'"$D"
echo ""
echo "$R""$bold"'ERROR WRONG COMMAND!'"$D"
echo ""
echo "$R""$bold"'ME DONT KNOW NOTHING!'"$D"
echo ""
sleep 3
wifi-leif-text ;;

esac
